#! /bin/sh -e
# This file is automatically generated with: tup generate make.sh
export tup_vardict="$(cd $(dirname $0) && pwd)/tup-generate.vardict"
(nt2json vars/Lavenoni.nt >vars/Lavenoni.json)
(PYTHONPATH=./templates wheezy.template templates/kde.colors.wz vars/Lavenoni.json >schemes/kde/Lavenoni.colors)
(PYTHONPATH=./templates wheezy.template templates/colors.tdesktop-theme.wz vars/Lavenoni.json >schemes/telegram/Lavenoni.tdesktop-theme)
