#! /bin/sh -e
# This file is automatically generated with: tup generate make.sh
export tup_vardict="$(cd $(dirname $0) && pwd)/tup-generate.vardict"
(nt2json vars/lavenoni.nt >vars/lavenoni.json)
(PYTHONPATH=./templates wheezy.template templates/kde.colors.wz vars/lavenoni.json >schemes/kde/lavenoni.colors)
