[tools]
python = "latest"
uv = "latest"
"ubi:ouch-org/ouch" = "latest"
"ubi:sharkdp/pastel" = "latest"

[env._.python]
venv = { path = ".venv", create = true }

[vars]
pip_compile = "uv pip compile --no-header --annotation-style=line"
unchanged = "git diff --exit-code -U0"
install_note = "printf '%s\n' 'To install the new versions:' '  mise run install'"

[tasks.remind-install-reqs]
hide = true
run = '''{{ vars.unchanged }} requirements.txt || {{vars.install_note}}'''

[tasks.lock-upgrade]
run = '''{{ vars.pip_compile }} -o requirements.txt -U requirements.in'''
depends_post = "remind-install-reqs"

[tasks.lock]
run = '''{{ vars.pip_compile }} -o requirements.txt requirements.in'''
depends_post = "remind-install-reqs"

[tasks.install]
run = '''uv pip sync requirements.txt'''

[tasks.make]
run = '''
#!/bin/sh -e
if command -v tup; then
  tup || printf '%s\n' 'You might try running:' '  mise run clean' 'and then again:' '  mise run make'
else
  printf '%s\n' "./make.sh"
fi
'''

[tasks.make-make]
run = '''tup generate make.sh'''

[tasks.clean]
run = '''
  for folder in tmp schemes; do
    rm -r "$folder" || true
  done
'''

[[watch_files]]
patterns = ["requirements.in"]
run = '''mise run lock'''

# TODO: subsume install.sh
